package fr.eseo.poo.projet.artiste.modele.formes;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;
import java.util.Collection;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import fr.eseo.poo.projet.artiste.modele.Coordonnees;

@RunWith(Parameterized.class)
public class EtoileTestParameterized {

	@Parameters(name = "dt[{index}] : {0}, {1}")
	public static Collection<Object[]> dt() {
		Object[][] data = new Object[][] { { new Coordonnees(0, 0), false }, { new Coordonnees(0, 5), false },
				{ new Coordonnees(0, 10), false }, { new Coordonnees(0, 15), false }, { new Coordonnees(0, 20), false },
				{ new Coordonnees(0, 25), false }, { new Coordonnees(0, 30), false }, { new Coordonnees(0, 35), false },
				{ new Coordonnees(0, 40), false }, { new Coordonnees(0, 45), false }, { new Coordonnees(0, 50), false },
				{ new Coordonnees(0, 55), false }, { new Coordonnees(0, 60), false }, { new Coordonnees(0, 65), false },
				{ new Coordonnees(0, 70), false }, { new Coordonnees(0, 75), false }, { new Coordonnees(0, 80), false },
				{ new Coordonnees(0, 85), false }, { new Coordonnees(0, 90), false }, { new Coordonnees(0, 95), false },
				{ new Coordonnees(0, 100), false }, { new Coordonnees(5, 0), false }, { new Coordonnees(5, 5), false },
				{ new Coordonnees(5, 10), false }, { new Coordonnees(5, 15), false }, { new Coordonnees(5, 20), false },
				{ new Coordonnees(5, 25), false }, { new Coordonnees(5, 30), false }, { new Coordonnees(5, 35), false },
				{ new Coordonnees(5, 40), false }, { new Coordonnees(5, 45), false }, { new Coordonnees(5, 50), false },
				{ new Coordonnees(5, 55), false }, { new Coordonnees(5, 60), false }, { new Coordonnees(5, 65), false },
				{ new Coordonnees(5, 70), false }, { new Coordonnees(5, 75), false }, { new Coordonnees(5, 80), false },
				{ new Coordonnees(5, 85), false }, { new Coordonnees(5, 90), false }, { new Coordonnees(5, 95), false },
				{ new Coordonnees(5, 100), false }, { new Coordonnees(10, 0), false },
				{ new Coordonnees(10, 5), false }, { new Coordonnees(10, 10), false },
				{ new Coordonnees(10, 15), false }, { new Coordonnees(10, 20), false },
				{ new Coordonnees(10, 25), false }, { new Coordonnees(10, 30), false },
				{ new Coordonnees(10, 35), false }, { new Coordonnees(10, 40), false },
				{ new Coordonnees(10, 45), false }, { new Coordonnees(10, 50), false },
				{ new Coordonnees(10, 55), false }, { new Coordonnees(10, 60), false },
				{ new Coordonnees(10, 65), false }, { new Coordonnees(10, 70), false },
				{ new Coordonnees(10, 75), false }, { new Coordonnees(10, 80), false },
				{ new Coordonnees(10, 85), false }, { new Coordonnees(10, 90), false },
				{ new Coordonnees(10, 95), false }, { new Coordonnees(10, 100), false },
				{ new Coordonnees(15, 0), false }, { new Coordonnees(15, 5), false },
				{ new Coordonnees(15, 10), false }, { new Coordonnees(15, 15), false },
				{ new Coordonnees(15, 20), false }, { new Coordonnees(15, 25), true },
				{ new Coordonnees(15, 30), true }, { new Coordonnees(15, 35), false },
				{ new Coordonnees(15, 40), false }, { new Coordonnees(15, 45), false },
				{ new Coordonnees(15, 50), false }, { new Coordonnees(15, 55), false },
				{ new Coordonnees(15, 60), false }, { new Coordonnees(15, 65), false },
				{ new Coordonnees(15, 70), true }, { new Coordonnees(15, 75), true },
				{ new Coordonnees(15, 80), false }, { new Coordonnees(15, 85), false },
				{ new Coordonnees(15, 90), false }, { new Coordonnees(15, 95), false },
				{ new Coordonnees(15, 100), false }, { new Coordonnees(20, 0), false },
				{ new Coordonnees(20, 5), false }, { new Coordonnees(20, 10), false },
				{ new Coordonnees(20, 15), false }, { new Coordonnees(20, 20), false },
				{ new Coordonnees(20, 25), true }, { new Coordonnees(20, 30), true }, { new Coordonnees(20, 35), true },
				{ new Coordonnees(20, 40), true }, { new Coordonnees(20, 45), false },
				{ new Coordonnees(20, 50), false }, { new Coordonnees(20, 55), false },
				{ new Coordonnees(20, 60), true }, { new Coordonnees(20, 65), true }, { new Coordonnees(20, 70), true },
				{ new Coordonnees(20, 75), true }, { new Coordonnees(20, 80), false },
				{ new Coordonnees(20, 85), false }, { new Coordonnees(20, 90), false },
				{ new Coordonnees(20, 95), false }, { new Coordonnees(20, 100), false },
				{ new Coordonnees(25, 0), false }, { new Coordonnees(25, 5), false },
				{ new Coordonnees(25, 10), false }, { new Coordonnees(25, 15), false },
				{ new Coordonnees(25, 20), false }, { new Coordonnees(25, 25), true },
				{ new Coordonnees(25, 30), true }, { new Coordonnees(25, 35), true }, { new Coordonnees(25, 40), true },
				{ new Coordonnees(25, 45), true }, { new Coordonnees(25, 50), true }, { new Coordonnees(25, 55), true },
				{ new Coordonnees(25, 60), true }, { new Coordonnees(25, 65), true }, { new Coordonnees(25, 70), true },
				{ new Coordonnees(25, 75), true }, { new Coordonnees(25, 80), false },
				{ new Coordonnees(25, 85), false }, { new Coordonnees(25, 90), false },
				{ new Coordonnees(25, 95), false }, { new Coordonnees(25, 100), false },
				{ new Coordonnees(30, 0), false }, { new Coordonnees(30, 5), false },
				{ new Coordonnees(30, 10), false }, { new Coordonnees(30, 15), false },
				{ new Coordonnees(30, 20), false }, { new Coordonnees(30, 25), true },
				{ new Coordonnees(30, 30), true }, { new Coordonnees(30, 35), true }, { new Coordonnees(30, 40), true },
				{ new Coordonnees(30, 45), true }, { new Coordonnees(30, 50), true }, { new Coordonnees(30, 55), true },
				{ new Coordonnees(30, 60), true }, { new Coordonnees(30, 65), true }, { new Coordonnees(30, 70), true },
				{ new Coordonnees(30, 75), true }, { new Coordonnees(30, 80), false },
				{ new Coordonnees(30, 85), false }, { new Coordonnees(30, 90), false },
				{ new Coordonnees(30, 95), false }, { new Coordonnees(30, 100), false },
				{ new Coordonnees(35, 0), false }, { new Coordonnees(35, 5), false },
				{ new Coordonnees(35, 10), false }, { new Coordonnees(35, 15), false },
				{ new Coordonnees(35, 20), false }, { new Coordonnees(35, 25), true },
				{ new Coordonnees(35, 30), true }, { new Coordonnees(35, 35), true }, { new Coordonnees(35, 40), true },
				{ new Coordonnees(35, 45), true }, { new Coordonnees(35, 50), true }, { new Coordonnees(35, 55), true },
				{ new Coordonnees(35, 60), true }, { new Coordonnees(35, 65), true }, { new Coordonnees(35, 70), true },
				{ new Coordonnees(35, 75), true }, { new Coordonnees(35, 80), false },
				{ new Coordonnees(35, 85), false }, { new Coordonnees(35, 90), false },
				{ new Coordonnees(35, 95), false }, { new Coordonnees(35, 100), false },
				{ new Coordonnees(40, 0), false }, { new Coordonnees(40, 5), false },
				{ new Coordonnees(40, 10), false }, { new Coordonnees(40, 15), false },
				{ new Coordonnees(40, 20), false }, { new Coordonnees(40, 25), false },
				{ new Coordonnees(40, 30), true }, { new Coordonnees(40, 35), true }, { new Coordonnees(40, 40), true },
				{ new Coordonnees(40, 45), true }, { new Coordonnees(40, 50), true }, { new Coordonnees(40, 55), true },
				{ new Coordonnees(40, 60), true }, { new Coordonnees(40, 65), true }, { new Coordonnees(40, 70), true },
				{ new Coordonnees(40, 75), false }, { new Coordonnees(40, 80), false },
				{ new Coordonnees(40, 85), false }, { new Coordonnees(40, 90), false },
				{ new Coordonnees(40, 95), false }, { new Coordonnees(40, 100), false },
				{ new Coordonnees(45, 0), false }, { new Coordonnees(45, 5), false },
				{ new Coordonnees(45, 10), false }, { new Coordonnees(45, 15), false },
				{ new Coordonnees(45, 20), false }, { new Coordonnees(45, 25), true },
				{ new Coordonnees(45, 30), true }, { new Coordonnees(45, 35), true }, { new Coordonnees(45, 40), true },
				{ new Coordonnees(45, 45), true }, { new Coordonnees(45, 50), true }, { new Coordonnees(45, 55), true },
				{ new Coordonnees(45, 60), true }, { new Coordonnees(45, 65), true }, { new Coordonnees(45, 70), true },
				{ new Coordonnees(45, 75), true }, { new Coordonnees(45, 80), false },
				{ new Coordonnees(45, 85), false }, { new Coordonnees(45, 90), false },
				{ new Coordonnees(45, 95), false }, { new Coordonnees(45, 100), false },
				{ new Coordonnees(50, 0), false }, { new Coordonnees(50, 5), false },
				{ new Coordonnees(50, 10), false }, { new Coordonnees(50, 15), false },
				{ new Coordonnees(50, 20), true }, { new Coordonnees(50, 25), true }, { new Coordonnees(50, 30), true },
				{ new Coordonnees(50, 35), true }, { new Coordonnees(50, 40), true }, { new Coordonnees(50, 45), true },
				{ new Coordonnees(50, 50), true }, { new Coordonnees(50, 55), true }, { new Coordonnees(50, 60), true },
				{ new Coordonnees(50, 65), true }, { new Coordonnees(50, 70), true }, { new Coordonnees(50, 75), true },
				{ new Coordonnees(50, 80), true }, { new Coordonnees(50, 85), false },
				{ new Coordonnees(50, 90), false }, { new Coordonnees(50, 95), false },
				{ new Coordonnees(50, 100), false }, { new Coordonnees(55, 0), false },
				{ new Coordonnees(55, 5), false }, { new Coordonnees(55, 10), false },
				{ new Coordonnees(55, 15), true }, { new Coordonnees(55, 20), true }, { new Coordonnees(55, 25), true },
				{ new Coordonnees(55, 30), true }, { new Coordonnees(55, 35), true }, { new Coordonnees(55, 40), true },
				{ new Coordonnees(55, 45), true }, { new Coordonnees(55, 50), true }, { new Coordonnees(55, 55), true },
				{ new Coordonnees(55, 60), true }, { new Coordonnees(55, 65), true }, { new Coordonnees(55, 70), true },
				{ new Coordonnees(55, 75), true }, { new Coordonnees(55, 80), true }, { new Coordonnees(55, 85), true },
				{ new Coordonnees(55, 90), false }, { new Coordonnees(55, 95), false },
				{ new Coordonnees(55, 100), false }, { new Coordonnees(60, 0), false },
				{ new Coordonnees(60, 5), false }, { new Coordonnees(60, 10), true }, { new Coordonnees(60, 15), true },
				{ new Coordonnees(60, 20), true }, { new Coordonnees(60, 25), true }, { new Coordonnees(60, 30), true },
				{ new Coordonnees(60, 35), true }, { new Coordonnees(60, 40), true }, { new Coordonnees(60, 45), true },
				{ new Coordonnees(60, 50), true }, { new Coordonnees(60, 55), true }, { new Coordonnees(60, 60), true },
				{ new Coordonnees(60, 65), true }, { new Coordonnees(60, 70), true }, { new Coordonnees(60, 75), true },
				{ new Coordonnees(60, 80), true }, { new Coordonnees(60, 85), true }, { new Coordonnees(60, 90), true },
				{ new Coordonnees(60, 95), false }, { new Coordonnees(60, 100), false },
				{ new Coordonnees(65, 0), false }, { new Coordonnees(65, 5), true }, { new Coordonnees(65, 10), true },
				{ new Coordonnees(65, 15), true }, { new Coordonnees(65, 20), true }, { new Coordonnees(65, 25), true },
				{ new Coordonnees(65, 30), true }, { new Coordonnees(65, 35), true }, { new Coordonnees(65, 40), true },
				{ new Coordonnees(65, 45), true }, { new Coordonnees(65, 50), true }, { new Coordonnees(65, 55), true },
				{ new Coordonnees(65, 60), true }, { new Coordonnees(65, 65), true }, { new Coordonnees(65, 70), true },
				{ new Coordonnees(65, 75), true }, { new Coordonnees(65, 80), true }, { new Coordonnees(65, 85), true },
				{ new Coordonnees(65, 90), true }, { new Coordonnees(65, 95), true },
				{ new Coordonnees(65, 100), false }, { new Coordonnees(70, 0), false },
				{ new Coordonnees(70, 5), false }, { new Coordonnees(70, 10), false },
				{ new Coordonnees(70, 15), false }, { new Coordonnees(70, 20), false },
				{ new Coordonnees(70, 25), false }, { new Coordonnees(70, 30), true },
				{ new Coordonnees(70, 35), true }, { new Coordonnees(70, 40), true }, { new Coordonnees(70, 45), true },
				{ new Coordonnees(70, 50), true }, { new Coordonnees(70, 55), true }, { new Coordonnees(70, 60), true },
				{ new Coordonnees(70, 65), true }, { new Coordonnees(70, 70), true },
				{ new Coordonnees(70, 75), false }, { new Coordonnees(70, 80), false },
				{ new Coordonnees(70, 85), false }, { new Coordonnees(70, 90), false },
				{ new Coordonnees(70, 95), false }, { new Coordonnees(70, 100), false },
				{ new Coordonnees(75, 0), false }, { new Coordonnees(75, 5), false },
				{ new Coordonnees(75, 10), false }, { new Coordonnees(75, 15), false },
				{ new Coordonnees(75, 20), false }, { new Coordonnees(75, 25), false },
				{ new Coordonnees(75, 30), false }, { new Coordonnees(75, 35), false },
				{ new Coordonnees(75, 40), true }, { new Coordonnees(75, 45), true }, { new Coordonnees(75, 50), true },
				{ new Coordonnees(75, 55), true }, { new Coordonnees(75, 60), true },
				{ new Coordonnees(75, 65), false }, { new Coordonnees(75, 70), false },
				{ new Coordonnees(75, 75), false }, { new Coordonnees(75, 80), false },
				{ new Coordonnees(75, 85), false }, { new Coordonnees(75, 90), false },
				{ new Coordonnees(75, 95), false }, { new Coordonnees(75, 100), false },
				{ new Coordonnees(80, 0), false }, { new Coordonnees(80, 5), false },
				{ new Coordonnees(80, 10), false }, { new Coordonnees(80, 15), false },
				{ new Coordonnees(80, 20), false }, { new Coordonnees(80, 25), false },
				{ new Coordonnees(80, 30), false }, { new Coordonnees(80, 35), false },
				{ new Coordonnees(80, 40), true }, { new Coordonnees(80, 45), true }, { new Coordonnees(80, 50), true },
				{ new Coordonnees(80, 55), true }, { new Coordonnees(80, 60), true },
				{ new Coordonnees(80, 65), false }, { new Coordonnees(80, 70), false },
				{ new Coordonnees(80, 75), false }, { new Coordonnees(80, 80), false },
				{ new Coordonnees(80, 85), false }, { new Coordonnees(80, 90), false },
				{ new Coordonnees(80, 95), false }, { new Coordonnees(80, 100), false },
				{ new Coordonnees(85, 0), false }, { new Coordonnees(85, 5), false },
				{ new Coordonnees(85, 10), false }, { new Coordonnees(85, 15), false },
				{ new Coordonnees(85, 20), false }, { new Coordonnees(85, 25), false },
				{ new Coordonnees(85, 30), false }, { new Coordonnees(85, 35), false },
				{ new Coordonnees(85, 40), false }, { new Coordonnees(85, 45), true },
				{ new Coordonnees(85, 50), true }, { new Coordonnees(85, 55), true },
				{ new Coordonnees(85, 60), false }, { new Coordonnees(85, 65), false },
				{ new Coordonnees(85, 70), false }, { new Coordonnees(85, 75), false },
				{ new Coordonnees(85, 80), false }, { new Coordonnees(85, 85), false },
				{ new Coordonnees(85, 90), false }, { new Coordonnees(85, 95), false },
				{ new Coordonnees(85, 100), false }, { new Coordonnees(90, 0), false },
				{ new Coordonnees(90, 5), false }, { new Coordonnees(90, 10), false },
				{ new Coordonnees(90, 15), false }, { new Coordonnees(90, 20), false },
				{ new Coordonnees(90, 25), false }, { new Coordonnees(90, 30), false },
				{ new Coordonnees(90, 35), false }, { new Coordonnees(90, 40), false },
				{ new Coordonnees(90, 45), true }, { new Coordonnees(90, 50), true }, { new Coordonnees(90, 55), true },
				{ new Coordonnees(90, 60), false }, { new Coordonnees(90, 65), false },
				{ new Coordonnees(90, 70), false }, { new Coordonnees(90, 75), false },
				{ new Coordonnees(90, 80), false }, { new Coordonnees(90, 85), false },
				{ new Coordonnees(90, 90), false }, { new Coordonnees(90, 95), false },
				{ new Coordonnees(90, 100), false }, { new Coordonnees(95, 0), false },
				{ new Coordonnees(95, 5), false }, { new Coordonnees(95, 10), false },
				{ new Coordonnees(95, 15), false }, { new Coordonnees(95, 20), false },
				{ new Coordonnees(95, 25), false }, { new Coordonnees(95, 30), false },
				{ new Coordonnees(95, 35), false }, { new Coordonnees(95, 40), false },
				{ new Coordonnees(95, 45), false }, { new Coordonnees(95, 50), true },
				{ new Coordonnees(95, 55), false }, { new Coordonnees(95, 60), false },
				{ new Coordonnees(95, 65), false }, { new Coordonnees(95, 70), false },
				{ new Coordonnees(95, 75), false }, { new Coordonnees(95, 80), false },
				{ new Coordonnees(95, 85), false }, { new Coordonnees(95, 90), false },
				{ new Coordonnees(95, 95), false }, { new Coordonnees(95, 100), false },
				{ new Coordonnees(100, 0), false }, { new Coordonnees(100, 5), false },
				{ new Coordonnees(100, 10), false }, { new Coordonnees(100, 15), false },
				{ new Coordonnees(100, 20), false }, { new Coordonnees(100, 25), false },
				{ new Coordonnees(100, 30), false }, { new Coordonnees(100, 35), false },
				{ new Coordonnees(100, 40), false }, { new Coordonnees(100, 45), false },
				{ new Coordonnees(100, 50), true }, { new Coordonnees(100, 55), false },
				{ new Coordonnees(100, 60), false }, { new Coordonnees(100, 65), false },
				{ new Coordonnees(100, 70), false }, { new Coordonnees(100, 75), false },
				{ new Coordonnees(100, 80), false }, { new Coordonnees(100, 85), false },
				{ new Coordonnees(100, 90), false }, { new Coordonnees(100, 95), false },
				{ new Coordonnees(100, 100), false }, };
		return Arrays.asList(data);
	}

	private Coordonnees point;

	private boolean result;

	public EtoileTestParameterized(Coordonnees coordonnees, boolean result) {
		this.point = coordonnees;
		this.result = result;
	}

	@Test
	public void contientTest() {
		Etoile etoile = new Etoile();
		assertEquals("Erreur contient" + point, result, etoile.contient(point));
	}

}
